import { Injectable, inject } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';
import { MatIconRegistry } from '@angular/material/icon';

@Injectable()
export class IconsClass {
  private iconRegistry = inject(MatIconRegistry);
  private sanitizer = inject(DomSanitizer);

  constructor() {
    this.iconRegistry.addSvgIcon(
      'account_circle',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-account_circle-24px.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'add_circle',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/add_circle_outline-24px.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'add',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/add_black_24dp.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'add_box',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/add_box_FILL0_wght400_GRAD0_opsz24.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'arrow_back',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/arrow_back-24px.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'arrow_forward',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/arrow_forward-24px.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'autorenew',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-autorenew-24px.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'block',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-block-24px.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'calendar',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/calendar_add_on_FILL0_wght400_GRAD0_opsz48.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'cake',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/cake_24dp_FILL0_wght400_GRAD0_opsz24.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'check',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-check-24px.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'account_circle_outline',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/outline-account_circle-24px.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'clock',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/schedule_FILL0_wght400_GRAD0_opsz48.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'clock_off',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/history_toggle_off_FILL0_wght400_GRAD0_opsz48.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'close',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/close_FILL0_wght400_GRAD0_opsz48.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'commute',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-commute-24px.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'dark_mode',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/dark_mode_FILL0_wght400_GRAD0_opsz24.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'delete',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-delete_forever-24px.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'directions',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-directions-24px.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'download',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/download_24dp_E8EAED_FILL0_wght400_GRAD0_opsz24.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'edit',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-edit-24px.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'email',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-email-24px.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'event',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-event_note-24px.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'gift',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/gift_24dp_FILL0_wght400_GRAD0_opsz24.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'heart',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/favorite_FILL0_wght400_GRAD0_opsz48.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'home',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-home-24px.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'hotel',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-hotel-24px.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'invitation',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-insert_invitation-24px.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'ios_share',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/ios_share_FILL0_wght400_GRAD0_opsz24.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'light_mode',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/light_mode_FILL0_wght400_GRAD0_opsz24.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'local_dining',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-local_dining-24px.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'location_on',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-location_on-24px.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'lock_open',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-lock_open-24px.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'lock',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-lock-24px.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'login',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/login_FILL0_wght400_GRAD-25_opsz24.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'logo',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/celebration_FILL0_wght400_GRAD0_opsz48.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'logout',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/logout_FILL0_wght400_GRAD-25_opsz24.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'loyalty',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-loyalty-24px.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'menu',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-menu-24px.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'more_vert',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-more_vert-24px.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'navigate_next',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/navigate_next_FILL0_wght400_GRAD0_opsz24.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'password',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/password_black_24dp.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'qr-code',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/qr_code_2_24dp_E8EAED_FILL0_wght400_GRAD0_opsz24.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'save',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-save-24px.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'settings',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/settings-24px.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'share',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/share-24px.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'space_dashboard',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/space_dashboard_black_24dp.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'space_dashboard_outlined',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/space_dashboard_FILL0_wght400_GRAD-25_opsz24.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'supervisor_account',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-supervisor_account-24px.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'supervisor_account_outline',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/outline-supervisor_account-24px.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'support',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/support_24dp_FILL0_wght400_GRAD0_opsz24.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'task',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/task_alt_24dp_FILL0_wght400_GRAD0_opsz24.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'timeline',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/timeline_24dp_FILL0_wght400_GRAD0_opsz24.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'upload',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/upload_FILL0_wght400_GRAD0_opsz48.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'visibility_off',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-visibility_off-24px.svg'
      )
    );
    this.iconRegistry.addSvgIcon(
      'visibility',
      this.sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-visibility-24px.svg'
      )
    );
  }
}
