import { Injectable } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';
import { MatIconRegistry } from '@angular/material/icon';

@Injectable()
export class IconsClass {
  constructor(iconRegistry: MatIconRegistry, sanitizer: DomSanitizer) {
    iconRegistry.addSvgIcon(
      'account_circle',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-account_circle-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'add_circle',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/add_circle_outline-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'add',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/add_black_24dp.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'add_box',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/add_box_FILL0_wght400_GRAD0_opsz24.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'arrow_back',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/arrow_back-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'arrow_forward',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/arrow_forward-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'autorenew',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-autorenew-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'block',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-block-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'calendar',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/calendar_add_on_FILL0_wght400_GRAD0_opsz48.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'cake',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/cake_24dp_FILL0_wght400_GRAD0_opsz24.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'check',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-check-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'account_circle_outline',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/outline-account_circle-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'clock',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/schedule_FILL0_wght400_GRAD0_opsz48.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'clock_off',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/history_toggle_off_FILL0_wght400_GRAD0_opsz48.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'close',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/close_FILL0_wght400_GRAD0_opsz48.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'commute',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-commute-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'dark_mode',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/dark_mode_FILL0_wght400_GRAD0_opsz24.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'delete',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-delete_forever-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'directions',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-directions-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'edit',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-edit-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'email',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-email-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'event',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-event_note-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'gift',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/gift_24dp_FILL0_wght400_GRAD0_opsz24.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'heart',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/favorite_FILL0_wght400_GRAD0_opsz48.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'home',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-home-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'hotel',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-hotel-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'invitation',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-insert_invitation-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'ios_share',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/ios_share_FILL0_wght400_GRAD0_opsz24.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'light_mode',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/light_mode_FILL0_wght400_GRAD0_opsz24.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'local_dining',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-local_dining-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'location_on',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-location_on-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'lock_open',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-lock_open-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'lock',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-lock-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'login',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/login_FILL0_wght400_GRAD-25_opsz24.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'logo',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/celebration_FILL0_wght400_GRAD0_opsz48.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'logout',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/logout_FILL0_wght400_GRAD-25_opsz24.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'loyalty',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-loyalty-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'menu',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-menu-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'more_vert',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-more_vert-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'navigate_next',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/navigate_next_FILL0_wght400_GRAD0_opsz24.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'password',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/password_black_24dp.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'qr-code',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/qr_code_2_24dp_E8EAED_FILL0_wght400_GRAD0_opsz24.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'save',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-save-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'settings',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/settings-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'share',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/share-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'space_dashboard',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/space_dashboard_black_24dp.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'space_dashboard_outlined',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/space_dashboard_FILL0_wght400_GRAD-25_opsz24.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'supervisor_account',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-supervisor_account-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'supervisor_account_outline',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/outline-supervisor_account-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'support',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/support_24dp_FILL0_wght400_GRAD0_opsz24.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'task',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/task_alt_24dp_FILL0_wght400_GRAD0_opsz24.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'timeline',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/timeline_24dp_FILL0_wght400_GRAD0_opsz24.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'upload',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/upload_FILL0_wght400_GRAD0_opsz48.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'visibility_off',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-visibility_off-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'visibility',
      sanitizer.bypassSecurityTrustResourceUrl(
        'material-icons/svg/baseline-visibility-24px.svg'
      )
    );
  }
}
